# coding: utf-8

"""
    IONOS Cloud - DNS API

    Cloud DNS service helps IONOS Cloud customers to automate DNS Zone and Record management. 

    The version of the OpenAPI document: 1.17.0
    Contact: support@cloud.ionos.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ionoscloud_dns.models.key_data import KeyData
from typing import Optional, Set
from typing_extensions import Self

class DnssecKey(BaseModel):
    """
    DnssecKey
    """ # noqa: E501
    key_tag: Optional[StrictInt] = Field(default=None, alias="keyTag")
    digest_algorithm_mnemonic: Optional[StrictStr] = Field(default=None, description="A string that denotes the digest algorithm. This value must conform to the guidelines in [RFC-8624 Section 3.3](https://datatracker.ietf.org/doc/html/rfc8624#section-3.3). ", alias="digestAlgorithmMnemonic")
    digest: Optional[StrictStr] = None
    key_data: Optional[KeyData] = Field(default=None, alias="keyData")
    composed_key_data: Optional[StrictStr] = Field(default=None, description="Represents the composed value of the The RDATA for a DNSKEY. The format should be the following: Flags | Protocol | Algorithm | Public Key The values must conform to the guidelines in [RFC-4034 Section 2.1](https://www.rfc-editor.org/rfc/rfc4034#section-2.1). ", alias="composedKeyData")
    __properties: ClassVar[List[str]] = ["keyTag", "digestAlgorithmMnemonic", "digest", "keyData", "composedKeyData"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DnssecKey from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of key_data
        if self.key_data:
            _dict['keyData'] = self.key_data.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DnssecKey from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "keyTag": obj.get("keyTag"),
            "digestAlgorithmMnemonic": obj.get("digestAlgorithmMnemonic"),
            "digest": obj.get("digest"),
            "keyData": KeyData.from_dict(obj["keyData"]) if obj.get("keyData") is not None else None,
            "composedKeyData": obj.get("composedKeyData")
        })
        return _obj


