# coding: utf-8

"""
    IONOS Cloud - DNS API

    Cloud DNS service helps IONOS Cloud customers to automate DNS Zone and Record management. 

    The version of the OpenAPI document: 1.17.0
    Contact: support@cloud.ionos.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from ionoscloud_dns.models.key_parameters import KeyParameters
from ionoscloud_dns.models.nsec_parameters import NsecParameters
from typing import Optional, Set
from typing_extensions import Self

class DnssecKeyParameters(BaseModel):
    """
    Parameters used to sign zone. 
    """ # noqa: E501
    key_parameters: Optional[KeyParameters] = Field(default=None, alias="keyParameters")
    nsec_parameters: Optional[NsecParameters] = Field(default=None, alias="nsecParameters")
    validity: Optional[Annotated[int, Field(le=365, strict=True, ge=90)]] = Field(default=None, description="Signature validity in days ")
    __properties: ClassVar[List[str]] = ["keyParameters", "nsecParameters", "validity"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DnssecKeyParameters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of key_parameters
        if self.key_parameters:
            _dict['keyParameters'] = self.key_parameters.to_dict()
        # override the default output from pydantic by calling `to_dict()` of nsec_parameters
        if self.nsec_parameters:
            _dict['nsecParameters'] = self.nsec_parameters.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DnssecKeyParameters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "keyParameters": KeyParameters.from_dict(obj["keyParameters"]) if obj.get("keyParameters") is not None else None,
            "nsecParameters": NsecParameters.from_dict(obj["nsecParameters"]) if obj.get("nsecParameters") is not None else None,
            "validity": obj.get("validity")
        })
        return _obj


